"""empty message

Revision ID: 2572441bb2f3
Revises: 1abcdef5e65d
Create Date: 2025-04-27 21:37:31.722338

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2572441bb2f3'
down_revision = '1abcdef5e65d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medications', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('patient', schema=None) as batch_op:
        batch_op.drop_column('medications')

    # ### end Alembic commands ###
