"""Renomeia upload_time para created_at no UploadedECG

Revision ID: 5a123b922667
Revises: dadc7b168534
Create Date: 2025-04-30 16:57:17.074476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a123b922667'
down_revision = 'dadc7b168534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_ecg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('upload_time')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('uploaded_ecg', schema=None) as batch_op:
        batch_op.add_column(sa.Column('upload_time', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True))
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###
